# The URL the site will be built for
base_url = "https://enerooo.cz"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true



[extra]
# Put all your custom variables here

[[extra.description_list]]
number = "images/1.svg"
number_alt = "Číslo 1"
description = "Řídící jednotka"
image = "images/ridici-jednotka.webp"
alt = "Řídící jednotka"

[[extra.description_list]]
number = "images/2.svg"
number_alt = "Číslo 2"
description = "Digitální elektroměr"
image = "images/digitalni-elektromer.webp"
alt = "Digitální elektroměr"

[[extra.description_list]]
number = "images/3.svg"
number_alt = "Číslo 3"
description = "Teplotní senzor"
image = "images/teplotni-cidlo.webp"
alt = "Teplotní senzor"

[[extra.description_list]]
number = "images/4.svg"
number_alt = "Číslo 4"
description = "Termostatická hlavice"
image = "images/termostaticka-hlavice.webp"
alt = "Termostatická hlavice"

[[extra.description_list]]
number = "images/5.svg"
number_alt = "Číslo 5"
description = "Chytrá zásuvka"
image = "images/chytre-zasuvky.webp"
alt = "Chytrá zásuvka"

[[extra.description_list]]
number = "images/6.svg"
number_alt = "Číslo 6"
description = "Rádiová brána"
image = "images/radiova-brana.webp"
alt = "Rádiová brána"

[[extra.description_list]]
number = "images/7.svg"
number_alt = "Číslo 7"
description = "Fotovoltaické panely"
image = "images/panel.webp"
alt = "Fotovoltaické panely"

[[extra.description_list]]
number = "images/8.svg"
number_alt = "Číslo 8"
description = "Solární invertor"
image = "images/invertor.webp"
alt = "Solární invertor"

[[extra.description_list]]
number = "images/9.svg"
number_alt = "Číslo 9"
description = "Centrální bojler"
image = "images/centralni-boiler.webp"
alt = "Centrální bojler"


[[extra.description]]
number = "images/1.svg"
number_alt = "Číslo 1"
header = "Řídící jednotka"
code = ["ER10E"]  # Použití seznamu s jedním prvkem
description = "Řídicí jednotka synchronizuje všechna zařízení systému ENEROOO pro maximální efektivitu. Připojuje se do ENEROOO cloudu přes LTE nebo Ethernet a funguje na platformě Linux."

[[extra.description]]
number = "images/2.svg"
number_alt = "Číslo 2"
header = "Digitální elektroměr"
code = ["ER10M", "ER11M", "ER12M"]  # Seznam více kódů
description = "Digitální elektroměry měří spotřebu jednotlivých bytů i u hlavního elektroměru domu, což zajišťuje spravedlivé rozdělení nákladů. Data odebírají každou minutu a poskytují přehled o spotřebě v reálném čase."

[[extra.description]]
number = "images/3.svg"
number_alt = "Číslo 3"
header = "Teplotní senzor"
code = ["ER10H"]
description = "Kompaktní bezdrátový senzor, který je napájen pomocí dvou AA baterií s životností přibližně dva roky. Komunikuje bezdrátově a je schopen přesně měřit teplotu."

[[extra.description]]
number = "images/4.svg"
number_alt = "Číslo 4"
header = "Termostatická hlavice"
code = ["ER10T"]
description = "Bezdrátová termohlavice umožňuje přesné nastavení teploty. Na displeji zobrazuje aktuální hodnoty a lze ji ovládat vzdáleně nebo ručně."

[[extra.description]]
number = "images/5.svg"
number_alt = "Číslo 5"
header = "Chytrá zásuvka"
code = ["ER10W", "ER11W"]  # Více kódů v seznamu
description = "Bezdrátová zásuvka umožňuje vzdálené i ruční ovládání. Automaticky se aktivuje při přetocích elektrické energie, což pomáhá optimalizovat spotřebu."

[[extra.description]]
number = "images/6.svg"
number_alt = "Číslo 6"
header = "Rádiová brána"
code = ["ER10G"]
description = "LoRaWAN brána spolehlivě sbírá data ze všech zařízení a bytů. Umožňuje snadné rozšíření systému o další prvky a je jednoduchá na instalaci."

[[extra.description]]
number = "images/7.svg"
number_alt = "Číslo 7"
header = "Fotovoltaické panely"
code = []  # Prázdný seznam, pokud žádný kód není
description = "Střešní fotovoltaické panely vyrábějí elektřinu, kterou sdílejí všechny bytové jednotky a společné prostory, což snižuje celkové náklady na energie."

[[extra.description]]
number = "images/8.svg"
number_alt = "Číslo 8"
header = "Solární invertor"
code = []
description = "Solární invertory převádějí energii z fotovoltaických panelů na střídavý proud, který lze přímo využít v domácnosti. Optimalizují výkon a zajišťují efektivní distribuci energie."

[[extra.description]]
number = "images/9.svg"
number_alt = "Číslo 9"
header = "Centrální bojler"
code = []
description = "Centrální ohřev vody využívá přebytky z fotovoltaických panelů, čímž snižuje náklady obyvatel. Zajišťuje chytré řízení teploty a bezdrátovou komunikaci bez rušení ze sítě."


[[extra.drop_down]]
title= "Kdo tvoří příběh ENEROOO"
description= [
        "<strong>HARDWARIO</strong> - Kompletní dodávka hardwaru a řídicího systému", 
        "<strong>Evolwings</strong> - Cloudové služby a vizualizace dat", 
        "<strong>Voltamyt</strong> - Referenční montáže a budování montážní sítě",
]

[[extra.drop_down]]
title= "Proč si vybrat ENEROOO?"
description= [
        "<strong>Úspora až 20 % nákladů na energii díky kombinaci solární energie a IoT technologií</strong>", 
        "<strong>Bezdrátové IoT sítě pro chytré řízení energetických zařízení</strong>", 
        "<strong>Reálný čas odečtu spotřeby pro větší kontrolu nad náklady</strong>",
]

[[extra.drop_down]]
title= "Chytré technologie v akci"
description= [
        "<strong>Odepínatelné zásuvky řízené výkonem solárního systému</strong>", 
        "<strong>Termostatické hlavice s dálkovým nastavením</strong>", 
        "<strong>Reálný čas odečtu energíí</strong>",
]