# The URL the site will be built for
base_url = "https://enerooo.cz"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true



[extra]
# Put all your custom variables here

[[extra.description_list]]
number = "images/1.svg"
number_alt = "Číslo 1"
description = "Řídící jednotka"
image = "images/enerooo-central-unit.webp"
alt = "Řídící jednotka"

[[extra.description_list]]
number = "images/2.svg"
number_alt = "Číslo 2"
description = "Digitální elektroměr"
image = "images/enerooo-digital-electricity-meter.webp"
alt = "Digitální elektroměr"

[[extra.description_list]]
number = "images/3.svg"
number_alt = "Číslo 3"
description = "Teplotní senzor"
image = "images/enerooo-temperature-sensor.webp"
alt = "Teplotní senzor"

[[extra.description_list]]
number = "images/4.svg"
number_alt = "Číslo 4"
description = "Termostatická hlavice"
image = "images/enerooo-thermostatic-head.webp"
alt = "Termostatická hlavice"

[[extra.description_list]]
number = "images/5.svg"
number_alt = "Číslo 5"
description = "Chytrá zásuvka"
image = "images/enerooo-smart-socket.webp"
alt = "Chytrá zásuvka"

[[extra.description_list]]
number = "images/6.svg"
number_alt = "Číslo 6"
description = "Rádiová brána"
image = "images/enerooo-radio-gateway.webp"
alt = "Rádiová brána"

[[extra.description_list]]
number = "images/7.svg"
number_alt = "Číslo 7"
description = "Fotovoltaické panely"
image = "images/enerooo-photovoltaic-panel.webp"
alt = "Fotovoltaické panely"

[[extra.description_list]]
number = "images/8.svg"
number_alt = "Číslo 8"
description = "Solární invertor"
image = "images/enerooo-solar-invertor.webp"
alt = "Solární invertor"

[[extra.description_list]]
number = "images/9.svg"
number_alt = "Číslo 9"
description = "Centrální bojler"
image = "images/enerooo-central-boiler.webp"
alt = "Centrální bojler"


[[extra.description]]
number = "images/1.svg"
number_alt = "Číslo 1"
header = "Řídící jednotka"
code = ["ER10E"]  # Použití seznamu s jedním prvkem
description = [
    "Synchronizace všech zařízení systému",
    "Připojení přes LTE nebo Ethernet",
    "Spolehlivý provoz na Linuxu"
]

[[extra.description]]
number = "images/2.svg"
number_alt = "Číslo 2"
header = "Digitální elektroměr"
code = ["ER10M", "ER11M", "ER12M"]  # Seznam více kódů
description = [
    "Měření spotřeby všech bytů",
    "Spravedlivé dělení nákladů",
    "Reálná data každou minutu"
]

[[extra.description]]
number = "images/3.svg"
number_alt = "Číslo 3"
header = "Teplotní senzor"
code = ["ER10H"]
description = [
    "Měření teploty",
    "Bezdrátová komunikace",
    "Životnost 2 roky"
]


[[extra.description]]
number = "images/4.svg"
number_alt = "Číslo 4"
header = "Termostatická hlavice"
code = ["ER10T"]
description = [
    "Bezdrátové nastavení teploty",
    "Zobrazení hodnot na displeji",
    "Ruční i vzdálené ovládání"
]


[[extra.description]]
number = "images/5.svg"
number_alt = "Číslo 5"
header = "Chytrá zásuvka"
code = ["ER10W", "ER11W"]
description = [
    "Vzdálené ovládání spotřebičů",
    "Aktivace při přetocích energie"
]


[[extra.description]]
number = "images/6.svg"
number_alt = "Číslo 6"
header = "Rádiová brána"
code = ["ER10G"]
description = [
    "Komunikace s rádiovými zařízeními",
    "Snadné rozšíření systému",
    "Rychlá a jednoduchá instalace"
]


[[extra.description]]
number = "images/7.svg"
number_alt = "Číslo 7"
header = "Fotovoltaické panely"
code = []
description = [
    "Výroba elektřiny pro byty",
    "Sdílení energie jednotkám",
    "Snížení celkových nákladů"
]


[[extra.description]]
number = "images/8.svg"
number_alt = "Číslo 8"
header = "Solární invertor"
code = []
description = [
    "Převod DC na AC energii",
    "Optimalizace výkonu panelů",
    "Efektivní distribuce elektřiny"
]


[[extra.description]]
number = "images/9.svg"
number_alt = "Číslo 9"
header = "Centrální bojler"
code = []
description = [
    "Ohřev vody z přebytků",
    "Chytré a efektivní řízení",
    "Spolehlivá bezdrátová komunikace"
]



[[extra.drop_down]]
title= "Kdo tvoří příběh ENEROOO"
description= [
        "<strong>HARDWARIO</strong> - Kompletní dodávka hardwaru a řídicího systému", 
        "<strong>Evolwings</strong> - Cloudové služby a vizualizace dat", 
        "<strong>Voltamyt</strong> - Referenční montáže a budování montážní sítě",
]

[[extra.drop_down]]
title= "Proč si vybrat ENEROOO?"
description= [
        "Úspora až 20 % nákladů na energii díky kombinaci solární energie a IoT technologií", 
        "Bezdrátové IoT sítě pro chytré řízení energetických zařízení", 
        "Reálný čas odečtu spotřeby pro větší kontrolu nad náklady",
]

[[extra.drop_down]]
title= "Chytré technologie v akci"
description= [
        "Odepínatelné zásuvky řízené výkonem solárního systému", 
        "Termostatické hlavice s dálkovým nastavením", 
        "Reálný čas odečtu energíí",
]

[[extra.drop_down]]
title= "Jaká řešení nabízíte pro bytové domy?"
description= [
        "Navrhujeme IoT systémy na míru pro řízení fotovoltaiky.", 
        "Zajišťujeme monitoring a správu spotřeby energie.",
]

[[extra.drop_down]]
title= "Pomáháte s optimalizací spotřeby energie?"
description= [
        "Poskytujeme přehled spotřeby v reálném čase.", 
        "Umožňujeme efektivní řízení vytápění, světel a dalších prvků.", 
]

[[extra.drop_down]]
title= "Je možné integrovat bateriová úložiště?"
description= [
        "Ano, fotovoltaiku lze propojit s bateriovými úložišti.", 
        "Nabízíme plné řízení a správu uložené energie.", 
]

[[extra.drop_down]]
title= "Jak je zajištěno spravedlivé měření?"
description= [
        "Každý uživatel má přehled o své vlastní spotřebě.", 
        "Spotřeba je spravedlivě měřena díky přesným digitálním elektroměrům.", 
]